name: Deploy Frontend (Next.js)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}

          script: |
            # Change directory to the project folder
            cd /www/wwwroot/frontend/MirexaStore

            # Use the full path for all commands to ensure they are found.
            echo "👉 Pulling latest code..."
            /usr/bin/git pull origin main

            echo "👉 Installing dependencies..."
            /home/yeasin_sarkar/.nvm/versions/node/v22.18.0/bin/npm install

            echo "👉 Building Next.js app..."
            /home/yeasin_sarkar/.nvm/versions/node/v22.18.0/bin/npm run build

            echo "👉 Restarting Next.js with PM2..."
            /home/yeasin_sarkar/.nvm/versions/node/v22.18.0/bin/pm2 restart mirexastore-frontend || /home/yeasin_sarkar/.nvm/versions/node/v22.18.0/bin/pm2 start npm --name "mirexastore-frontend" -- run start
